aallam/openai-kotlin

README.md
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Edits.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/OpenAIApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/EditsApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestOpenAI.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/completion/Choice.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/edits/EditsRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/edits/EditsResponse.kt

| Related Issue     | Fix #14   
| Need Doc update   | no
Implementation of [edits](https://beta.openai.com/docs/api-reference/edits) api.

feat: edits

---

README.md
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Embeddings.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/OpenAIApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/EmbeddingsApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestOpenAI.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/embedding/Embedding.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/embedding/EmbeddingRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/embedding/EmbeddingResponse.kt

| Related Issue     | Fix #12   
| Need Doc update   | yes
Implementation of [embeddings](https://beta.openai.com/docs/api-reference/embeddings) api.

feat: embeddings

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/Answers.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Classifications.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Searches.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/OpenAIApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AnswersApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ClassificationsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/SearchesApi.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/answer/Answer.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/answer/AnswerRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/answer/Document.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/answer/QuestionAnswer.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/answer/internal/QuestionAnswerSerializer.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/classification/Classification.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/classification/ClassificationRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/classification/Example.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/classification/LabeledExample.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/classification/internal/LabeledExampleSerializer.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/search/SearchRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/search/SearchResponse.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/search/SearchResult.kt

| Related Issue     | n/a  
| Need Doc update   | no
Blog post: [Answers, Classification, Search Endpoint Deprecation](https://community.openai.com/t/answers-classification-search-endpoint-deprecation/18532)

chore: Answers, Classification, and Search Deprecation

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
gradle/libs.versions.toml
openai-client/build.gradle.kts
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ClassificationsApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestOpenAI.kt

| Related Issue     | n/a.  
| Need Doc update   | no

fix: edits tests

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/Models.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/OpenAIApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ModelsApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestOpenAI.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/model/Model.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/model/ModelId.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/model/ModelPermission.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/model/ModelsResponse.kt

| New feature?      | yes   
| Related Issue     | n/a  
Implementation of [models](https://beta.openai.com/docs/api-reference/models) API.

feat: `Models` API implementation

---

README.md
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Models.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ModelsApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestOpenAI.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/completion/CompletionRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/completion/TextCompletion.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/edits/EditsRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/embedding/EmbeddingRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/embedding/EmbeddingResponse.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/model/Model.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/model/ModelId.kt
sample/js/src/main/kotlin/main.kt
sample/jvm/src/main/kotlin/com/aallam/openai/sample/jvm/App.kt
sample/native/src/nativeMain/kotlin/main.kt

feat(models): model id as value class

---

gradle/wrapper/gradle-wrapper.properties
openai-client/build.gradle.kts
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/HttpClient.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/http/Timeout.kt

Add `Timeout` configuration for http request, connect and socket.

feat: add configurable timeouts

---

build-support/src/main/kotlin/Platforms.kt
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
openai-client/build.gradle.kts
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestOpenAI.kt

chore: add darwin targets

---

README.md
openai-client-bom/README.md

| New feature?      | yes/no    
| Related Issue     | Fix #77
Update `README.md` to use generic `<version>`

chore: use generic tag for version number

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/HttpClient.kt

Add the following to `OpenAIConfig`

feat: configurable headers and org

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/Images.kt

refactor(images): mark as experimental

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/FineTunes.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FineTunesApi.kt

refactor(fine-tunes): remove experimental flag

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/HttpClient.kt

| New feature?      | yes/no    
| Related Issue     | Fix #110 
Add `ProxyConfig` class and `OpenAIConfig.proxy`

feat(config): add proxy config

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt

| Related Issue     | Fix #116 
Fixes `OpenAIConfig` kdoc.

fix: openai config docs [skip ci]

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/HttpClient.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FilesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/http/HttpTransport.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestException.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/exception/OpenAIException.kt

refactor: simplify and add more exceptions

---

CHANGELOG.md
openai-client/build.gradle.kts
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/OpenAIApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/http/HttpRequester.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/http/HttpTransport.kt

feat: `OpenAI` implements `AutoCloseable`

---

.github/workflows/build.yml
.github/workflows/publish-snapshot.yml
.github/workflows/publish.yml

`wrapper` is the default value of `gradle-version`.

Tweak gradle-build-action params

---

README.md

Follow up #149, inspired by [OkHttp did](https://square.github.io/okhttp/features/r8_proguard/).

Update README for ProGuard section

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/completion/CompletionRequest.kt

| New feature?      | yes   
| Related Issue     | Fix #171 
Add `suffix` request parameter to `CompletionRequest`.

feat(completion): add `suffix` request param

---

openai-client/build.gradle.kts
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Closeable.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/OpenAIApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/http/HttpRequester.kt
openai-client/src/jsMain/kotlin/com/aallam/openai/client/Closeable.kt
openai-client/src/jvmMain/kotlin/com/aallam/openai/client/Closeable.kt
openai-client/src/nativeMain/kotlin/com/aallam/openai/client/Closeable.kt

| Related Issue     | Fix #170 
Remove the use of `AutoCloseable` until it's stable.

fix: remove the use of experimental autocloseable

---

README.md

| Related Issue     | 
I added a section `Troubleshooting` to the doc to clarify how to use the library with GPT-4.
I didn't join the waitlist 😬 and I was seeing an error in the logs. I think this can help other devs as well.

Add a note to the doc about GPT-4 API access.

---

guides/ChatFunctionCall.md

| Related Issue     | Fix #207

docs(chat): update function params builder code snippet

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/audio/Segment.kt

Made Segment's transient property and added default value 'null' 

---

README.md
guides/GettingStarted.md

1. Added Maven set up section to README
1. Added custom hosts section to GettingStarted
1. Fixed typo in "multiplatform"
1. Fixed typo in "troubleshooting"
1. Fixed trailing `-` typo in moderations section
I just stumbled upon this library recently and love it. Thought I would contribute a couple of new sections to the documentation that (as a noob myself) a noob might be looking for. 
Also fixed several small typos.

Add documentation for Maven and custom hosts

---

openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestChatCompletions.kt

chore(chat): fix flaky json test

---

CHANGELOG.md
openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/MessageFile.kt

| Related Issue     | Fix #289

fix(message): message file optional fields

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RunRequest.kt

Just add a new property `additionalInstructions` in the assistant run request.

Add additional_instructions property into Assistant->Run->RunRequest

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AssistantsApi.kt

| Related Issue     | Fix #297 
Just changed the URL to match the API reference

fix https://github.com/aallam/openai-kotlin/issues/297

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/ImageCreation.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/Quality.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/internal/ImageCreationRequest.kt

`Quality` should be in the `com.aallam.openai.api.image` package

fix: correct Quality package name

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionChunk.kt

| Related Issue     | Fix #299

fix(chat): add `systemFingerprint` to `ChatCompletionChunk`

---

CHANGELOG.md
openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/ImageFile.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/MessageContent.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/MessageFile.kt

| Related Issue     | Fix #312, #307

fix(messages): content as image file

---

CHANGELOG.md
openai-core/src/commonMain/kotlin/com.aallam.openai.api/exception/OpenAIErrorDetails.kt

| Related Issue     | Fix #308

fix(core): nullable `OpenAIErrorDetails` fields

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/Quality.kt

| BC breaks?        | yes
| Related Issue     | Fix #316 
Remove `Quality.kt` file completely.

fix: remove quality typealias

---

CHANGELOG.md
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/extension/HttpRequestBuilder.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/misc/TestRequestOptions.kt

fix(requestOptions): headers override previous values

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/RunsApi.kt

| Related Issue     | Fix #348

fix(runs): get runs order param serialization

---

CHANGELOG.md
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestChatCompletions.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/StreamOptions.kt

| Related Issue     | Fix #347

feat(chat): add stream options

---

.gitignore
build-support/build.gradle.kts
build-support/src/main/kotlin/Platforms.kt
gradle.properties
gradle/libs.versions.toml
openai-client/build.gradle.kts
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/CompletionsApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestFiles.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestFineTuning.kt
openai-client/src/jvmMain/kotlin/com/aallam/openai/client/Closeable.kt
openai-client/src/wasmJsMain/kotlin/com.aallam.openai.client/Closeable.wasmJs.kt
openai-core/build.gradle.kts
settings.gradle.kts

I have added the wasmjs target to the project.
Supports the new wasmjs target.

Wasmjs upgrade

---

gradle/libs.versions.toml
settings.gradle.kts

| Related Issue     | Fix #384
Update Ktor to stable v3.

feat(ktor): update to stable v3

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionRequest.kt

Make ChatCompletionRequest a data class
Make ChatCompletionRequest copy method available for easier request modification

Make ChatCompletionRequest a data class

---

guides/GettingStarted.md

| Bug fix?          | yes/no
| New feature?      | yes/no    
| Related Issue     | Fix #...

fix out-of-date reference to RetrievalTool — GettingStarted.md
