gradle.properties
openai-core/src/commonMain/kotlin/com.aallam.openai.api/completion/CompletionRequest.kt

See documentation: https://beta.openai.com/docs/api-reference/completions/create
Version bump to 1.0.1
Please let me know if there's something else I should do, or if I contributed incorrectly in some way.

refact: add user to CompletionRequest

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FineTunesApi.kt

| New feature?      | no 
| Related Issue | n/a
Although currently implemented as a `POST` operation, the docs indicate that the `stream` parameter should be provided as a query parameter on the `GET` operation: https://beta.openai.com/docs/api-reference/fine-tunes/events#fine-tunes/events-stream.
Currently, invoking the `fineTuneEventsFlow` invariably yields at `403` response from openai.

Fix FineTunesApi event streaming invocation.

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/CompletionsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FineTunesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/extension/Stream.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/http/HttpRequester.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/http/HttpTransport.kt

| Related Issue     | Fix #94   
Start emitting flow events without waiting for the full HTTP response using `HttpStatement.execute`.
Based on Ktor's [documentation](https://ktor.io/docs/response.html#streaming), `HttpResponse.body` waits for the full response before returning a result (including `HttpResponse.body<ByteReadChannel>()` and `response.bodyAsChannel()`), whch is not the desired behavior.

fix: start emit flow without waiting for SSE full response

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/HttpClient.kt

| Related Issue     | Fix #100 
- Add `OpenAIHost` with two params: `baseUrl` and `queryParams`
- Add `host` param to `OpenAIConfig`

feat(config): add custom host config

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/HttpClient.kt

| Related Issue     | Fix #107 
- Add request retry in case of rate limit errors (following the [docs](https://help.openai.com/en/articles/6891753-rate-limit-advice) recommendations).
- Add `RetryStrategy` and `OpenAIConfig.retry`

feat(config): add retry strategy in case of rate limit

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AudioApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestAudio.kt

| Related Issue     | Fix #118
This change switches the mixed-up paths for audio translation and transcription and also fixes the translation test.
The translation and transcription paths in https://github.com/aallam/openai-kotlin/blob/main/openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AudioApi.kt are mixed up.

fix: switch mixed-up audio translation and transcription paths

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionRequest.kt

| Related Issue     | Fix #126 
Add missing `user` param to `ChatCompletionRequest`

feat(chat): add user param to chat request

---

README.md

| New feature?      |no    
| Related Issue     |  
Corrected gradle configuration file name in README.md from `gradle.build` to `build.gradle`.

fix: correct gradle configuration file name in README.md

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/http/HttpTransport.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/exception/OpenAIAPIException.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/exception/OpenAIException.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/exception/OpenAIIOException.kt

Throw `IOException` as `GenericIOException` instead of `OpenAIHttpException`

refact: add generic io exception

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ApiPath.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AudioApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ChatApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/CompletionsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/EditsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/EmbeddingsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FilesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FineTunesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ImagesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ModelsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ModerationsApi.kt

| Related Issue     | Fix #195

feat(host): add support of azure hosts

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/FunctionMode.kt
openai-core/src/commonTest/kotlin/com.aallam.openai.api/chat/TestFunctionMode.kt

Update `FunctionModeSerializer` to read `name` from the decoded `JsonObject`.
`FunctionModeSerializer`, when processing `FunctionMode.Named`, attempts to decode twice, which results in an exception. See included test, `TestFunctionMode`.

fix: function mode serializer

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/moderation/TextModeration.kt

feat(moderations): add harassment and self-hard categories and scores

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/extension/ChatChuck.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/extension/internal/ChatMessageAssembler.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestChatChunk.kt
sample/jvm/src/main/kotlin/com/aallam/openai/sample/jvm/ChatFunctionCall.kt

Add `mergeToChatMessage`, a helper function to merge list of `ChatChunk` into`ChatMessage`

feat: add `mergeToChatMessage`

---

CHANGELOG.md
README.md
guides/GettingStarted.md
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ImagesApi.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/ImageCreation.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/ImageEdit.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/ImageVariation.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/internal/ImageCreationRequest.kt

Allow to specify custom model for image creation, variations and edit as described in [API doc](https://platform.openai.com/docs/api-reference/images/createEdit) after recent update (REST API added support for DALL-E 3 model - https://help.openai.com/en/articles/8555480-dall-e-3-api)

feat(images): add support for model selection

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAIConfig.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/HttpClient.kt

| Related Issue     | Fix #260
Add the possibility to explicit provided a HttpEngine avoid the internal Ktor initialization using ServiceLoader.
Unable to use the API in a Kotlin Script.

feat: adding ktor engine config to support Kotlin Scripting

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt

Added missing `Runs` & `Messages` interfaces to `OpenAI`.

fix: add missing Runs & Messages to OpenAI

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RequiredAction.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/ToolOutputs.kt

Fixes `Field 'tool_calls' is required for type with serial name 'submit_tool_outputs', but it was missing`. API states that required action is the parent object:

fix: field 'tool_calls' is required for type with serial name 'submit_tool_outputs', but it was missing

---

openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestAssistants.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestRuns.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RunStep.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RunStepDetails.kt
sample/jvm/src/main/kotlin/com/aallam/openai/sample/jvm/Assistants.kt

| Related Issue     | Fix #267

fix(runs): run steps deserialization

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RunStepDetails.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/ToolCallStepId.kt

Fixes:
```
Caused by: kotlinx.serialization.MissingFieldException: Fields [name, arguments] are required for type with serial name 'function', but they were missing
at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
at com.aallam.openai.api.run.ToolCallStep$FunctionTool.<init>(RunStepDetails.kt:87)
at com.aallam.openai.api.run.ToolCallStep$FunctionTool$$serializer.deserialize(RunStepDetails.kt:87)
at com.aallam.openai.api.run.ToolCallStep$FunctionTool$$serializer.deserialize(RunStepDetails.kt:87)
```

fix: MissingFieldException: Fields [name, arguments] in ToolCallStep$FunctionTool

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RunStepDetails.kt

Previous change renamed `name` to `id` instead of adding new `id` field. This adds `name` back to `FunctionToolCallStep`.

 chore: add missing name field to `FunctionToolCallStep`

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/Run.kt

Noticed that my polling loop wouldn't stop when canceling a run and found that the property name didn't match when looking at the response body.
See https://platform.openai.com/docs/api-reference/runs/object#runs/object-cancelled_at - not sure if this was a typo in the library or if OpenAI changed this at some point.

Fix incorrect property name (Run.canceledAt -> cancelledAt)

---

openai-core/src/jvmMain/resources/META-INF/proguard/openai.pro

Add an extra proguard rule `-keepattributes EnclosingMethod` which is required by the `InnerClasses` attribute rule. 
On Android, the `-keepattributes InnerClasses` proguard rule complains about missing `EnclosingMethod` attribute causing release builds with minification enabled to fail.

Add EnclosingMethod proguard rule

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/completion/Choice.kt

| Related Issue     | Fix #284

fix(completion): `Choice.finishReason` as nullable

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ImagesApi.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/ImageCreation.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/Quality.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/Style.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/image/internal/ImageCreationRequest.kt

| New feature?      | yes/    
| Related Issue     | Fix #291

feat(image): add `quality` and `style` fields

---

CHANGELOG.md
gradle.properties
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Assistants.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Audio.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Chat.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Embeddings.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Files.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/FineTuning.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Images.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Messages.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Models.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Moderations.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Runs.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/Threads.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AssistantsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AudioApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ChatApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/EmbeddingsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FilesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/FineTuningApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ImagesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/MessagesApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ModelsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ModerationsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/RunsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/ThreadsApi.kt
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/extension/HttpRequestBuilder.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/misc/TestRequestOptions.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/core/RequestOptions.kt

| Related Issue     | Fix #295 
Add `RequestOptions` to all non-deprecated methods.
This adds the capability to override headers, URL parameters, and timeouts on a per-request basis.

feat: add `RequestOptions`

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/Tool.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/finetuning/ErrorInfo.kt

| Bug fix?          | yes/no
| New feature?      | yes/no    
| Related Issue     | Fix #301
- fix(chat): move `description` to `FunctionTool`
- fix(chat): make `FunctionTool#Parameters` nullable
- fix(finetuning): nullable `ErrorInfo#message` and `ErrorInfo#code`

fix(chat): refactor and fix `Tool`

---

CHANGELOG.md
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/AudioApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestAudio.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/audio/TimestampGranularity.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/audio/Transcription.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/audio/TranscriptionRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/audio/Word.kt

The transcription requests got a new parameter `timestamp_granularities` recently (added to openai-python a month ago), which allows to get word timestamps. These changes add support for the parameter and for the corresponding `words` field in the response.
I've tested the correctness with a new test using API key (but excluded all other tests to save quota).
Lack of support for word timestamps in transcriptions.

Add timestamp_granularities

---

openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestEmbeddings.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/embedding/EmbeddingRequest.kt

| Related Issue     | None
This adds the `dimensions` request field available when creating embeddings with the new `text-embedding-3` models.
https://platform.openai.com/docs/api-reference/embeddings/create?lang=curl
The field was missing and i wanted to use it :)

Add embedding dimensions request field

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatMessage.kt

This fixes issue #320 invalid value: 'image'. Supported values are: 'text' and 'image_url' (https://github.com/aallam/openai-kotlin/issues/320)
| Related Issue     | Fix #320
This fix correct the wrong contentpart type "Image" to the correct one "image_url"
This problem fixes issue #320

Fix issue https://github.com/aallam/openai-kotlin/issues/320 (Invalid value: 'image'. Supported values are: 'text' and 'image_url')

---

openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestChatCompletions.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatChoice.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletion.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/Logprobs.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/LogprobsContent.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/TopLogprob.kt

| Related Issue     | Fix #326 
Wanted to be able to get the logprobs in the response from openai. It looks like its a non beta feature exposed in the chat completion object
https://platform.openai.com/docs/api-reference/chat/object
I've attempted to capture it as specified, and verified that top_logprobs is provided whether we do or do not limit how many are returned as denoted in the test.
Closing the gap between what openai has exposed and what is supported.
Should be resolving: https://github.com/aallam/openai-kotlin/issues/326

feat(chat-completions): Add Logprobs for ChatCompletions

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/model/Model.kt

| BC breaks?        | not sure
| Related Issue     | Fix #331
This change was suggested by GPT-4 as I don't know Kotlin. Moreover I don't know how openai-kotlin was engineered so I don't know if that breaks backward compatibility or if some parts of the lib rely on the fields `created` and `owned-by` to exist.
In issue #331 I reported that listing models fails with the endpoint of openrouter because those two keys are missing. To me supporting openrouter.ai would really be awesome because they support [many many many models](https://openrouter.ai/docs#models) including from OpenAI, Anthropic, Cohere, Mistral, Google, etc. So even the bare minimum amount of compatibility (listing …

untested fix: make .models() call not crash if created or owned_by are missing in some endpoints (openrouter)

---

CHANGELOG.md
openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/extension/Stream.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestChatCompletions.kt

| Related Issue     | Fix #329
Enhance SSE based Flows cancellation

feat(chat): enhance flow cancel capability

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/assistant/Assistant.kt

Trying to list assistants currently fails if one of them has no name.
https://platform.openai.com/docs/api-reference/assistants/createAssistant#assistants-createassistant-name

Assistant.name is nullable

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatChunk.kt

| Related Issue     | 
Default `ChatChunk.finishReason` to null. This should allow us to support more service providers.
Currently, `ChatChunk.finishReason` is declared as nullable but does not have a default value. Serialization complains that the field is missing.
```
Caused by: [CIRCULAR REFERENCE: com.aallam.openai.api.exception.OpenAIHttpException: Field 'finish_reason' is required for type with serial name 'com.aallam.openai.api.chat.ChatChunk', but it was missing at path: $.choices[0]]
```

Default `ChatChunk.finishReason` to null

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/internal/api/RunsApi.kt
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestRuns.kt

| Related Issue     | Fix #356   
- updated beta version for Runs API too
- Requesting parameters haven't changed
- modified test of TestRun to use gpt-4o / it also needed message to make a run from v2, so I added test message too
Using 'run' api for gpt-4o model also depends on beta version-v2

fix(runs): beta-v2 hotfix - Runs need v2 version to use gpt-4o

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionRequest.kt

| Related Issue     | 
Adds an instanceID field in ChatCompletionRequest which can be used to target a specific multi LoRA reserved instance. 
Sample curl command:
`curl -X POST https://api.openai.com/v1/chat/completions -H "Authorization: Bearer $OPENAI_API_KEY" -d '{"messages": [{"role":"user", "content": "how do i tie my shoes?"}], "model":"gpt-3.5-turbo-1106", "instance_id": "gpt-3.5-turbo-1106-instance"}' -H 'Content-Type: application/json'`
There's no option currently to target a specific instance/fleet in OpenAI, especially if using multi LoRA.

Add instanceId field to ChatCompletionRequest

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/Run.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RunRequest.kt

I added the new fields into Run the object.

Add new fields into assistant run

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/Attachment.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/MessageRequest.kt

| New feature?      | yes   
| Related Issue     |
Adds an optional `attachments.fileId` field in MessageRequest that can be used to specify attachment file in message API.
You can check [here](https://platform.openai.com/docs/api-reference/messages/createMessage#messages-createmessage-attachments) for its API reference.
currently not able to specify attachment file using [create message](https://platform.openai.com/docs/api-reference/messages/createMessage) API.

feat(assistants): add `attachments.fileId` field to `MessageRequest`

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/MessageContent.kt

| New feature?      | no 
| Related Issue     | Fix #368 
Make `quote` field in FileCitation nullable 
Exception in serialization if there is no quote field in response json

fix #368 serialization exception while retrieving thread messages

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/Attachment.kt

feat(messages): add assistant tools to attachements

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/message/MessageContent.kt

| New feature?      | no   
Change field 'quote' on com.aallam.openai.api.message.FileCitation nullable with no-value
In openai API for assistants module, api can't return type quote 
Tested and works !

fix 'quote' to optional field for openai compatibility assistant on FileCitation

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionChunk.kt

Unix timestamps should be longs.
ChatCompletion.created is Long (https://platform.openai.com/docs/api-reference/chat/object#chat/object-created) but ChatCompletionChunk.created is Int (https://platform.openai.com/docs/api-reference/chat/streaming#chat/streaming-created) even though they hold the same data.

Make ChatCompletionChunk.created long

---

CHANGELOG.md
openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestChatCompletions.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatResponseFormat.kt

| Related Issue     | Fix #397 
Allow specifying JSON schema for chat completions. See the added unit test (jsonSchema in TestChatCompletions) for a simple example of how to use. 
Note: This feature is only available for models 4o and later.
OpenAI's API supports specifying JSON schema for recent models. This library does not currently allow the user to specify this, and now it will. 
One benefit is that (as can be seen in the added unit test), you do not have to specify the schema in the messages themselves now.

Allow specifying JSON schema for chat completions

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/run/RunStepDetails.kt

| Related Issue     | Fix #404 
Adds `FileSearchTool` to the `ToolCallStep` enum, along with `FileSearchToolCallStep` and other nested objects.
When trying to fetch runSteps for a Run that contained any `file_search` tool calls, the response would fail due to serialization issues.

fix: support for file search tool calls

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatCompletionRequest.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/Effort.kt

| Related Issue     | Fix #...  
`o3-mini` was released yesterday, and there are several changes to the API.
- Added `reasoning_effort` parameter: This is used to give the model guidance on how many reasoning tokens it should generate before creating a response to the prompt. See [here](https://platform.openai.com/docs/guides/reasoning#reasoning-effort) for more information.
- Deprecated `max_tokens` and add `max_completion_tokens`: This parameter is no longer supported in reasoning models.  See [here](https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens) for more information.
- Add `store` parameter: Option to store the …

Add reasoning effort, max completion tokens, store options for reasoning model support

---

openai-client/src/commonMain/kotlin/com.aallam.openai.client/OpenAI.kt

| Related Issue     | Fix #383 ...  
Since version 3.8.0 there is a Batch Api implemented. Though it is not accessible via OpenAI interface
This PR makes OpenAI interface extend Batch interface
When you create an instance of OpenAI class using function OpenAI(...), you can't access batch api like `openAI.batch(...), because it doesn't extend it.

Make OpenAi interface extend Batch interface

---

openai-client/src/commonTest/kotlin/com/aallam/openai/client/TestChatCompletions.kt
openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ChatResponseFormat.kt

1.  Make `strict` to be encoded when it is set to `true` in `JsonSchema`
2. Add `additionalProperties` to `jsonSchema()` test, as it is required when `strict` is `true`
`strict` `true` in `JsonSchema` was never encoded to json since kotlin Json does not encode default values so openai thinks its `false` by default
When `strict` is `false` and schema has nested classes or lists then `ChatMessage` `content` gets wrapped in extra object like `content": "{\"type\":\"object\",\"properties\":{\"isValid\":true,...` 
instead of  expected `"content": "{\"isValid\":true,...`

Fix JsonSchema strict to be encoded even if it's default value is true

---

openai-core/src/commonMain/kotlin/com.aallam.openai.api/chat/ToolChoice.kt

| Related Issue     | Fix #424 
Define toolchoice for `required` to be in compliance with the documented API specifications mentioned at https://platform.openai.com/docs/guides/function-calling#additional-configurations
The inability to easily choose Required as a tool choice option when working with OpenAI APIs

Update to support required toolchoice mode
